In [17]:
import pandas as pd

In [18]:
paper_affiliation = pd.read_csv('./DATA/paper_affiliation_10_seq.csv')
affiliation_country = pd.read_csv('./DATA/affiliation_name.csv').drop(columns='Unnamed: 0', axis=1).rename(columns={"affid" : "Affiliation"})

In [19]:
paper_affiliation

                      Eid  Affiliation
0      2-s2.0-85053164279     60018465
1      2-s2.0-85053164279     60091507
2      2-s2.0-85049101440     60028190
3      2-s2.0-85054140369     60017165
4      2-s2.0-85054140369     60026046
...                   ...          ...
61387  2-s2.0-85150789915     60013939
61388  2-s2.0-85150789915     60199578
61389  2-s2.0-85165609857     60028190
61390  2-s2.0-85164405594     60105841
61391  2-s2.0-85164405594     60028190

[61392 rows x 2 columns]

In [20]:
paper_affiliation.drop_duplicates()

                      Eid  Affiliation
0      2-s2.0-85053164279     60018465
1      2-s2.0-85053164279     60091507
2      2-s2.0-85049101440     60028190
3      2-s2.0-85054140369     60017165
4      2-s2.0-85054140369     60026046
...                   ...          ...
61387  2-s2.0-85150789915     60013939
61388  2-s2.0-85150789915     60199578
61389  2-s2.0-85165609857     60028190
61390  2-s2.0-85164405594     60105841
61391  2-s2.0-85164405594     60028190

[61392 rows x 2 columns]

In [21]:
affiliation_country

,_id,Affiliation,affname,location,Country
0,674efcc87ab4fa1176e75fa4,60278391,Kyiv Academic University,"36 Vernadsky blvd., Kyiv, Ukraine",Ukraine
1,674efcc97ab4fa1176e75fa5,60278325,"The Catholic University of Korea, College of N...","222 Banpo-daero Seocho-gu, Seoul, South Korea",South Korea
2,674efcca7ab4fa1176e75fa6,60278195,Beijing Institute of Genomics Chinese Academy ...,"NO.1 Beichen West Road, Chaoyang District, Bei...",China
3,674efccc7ab4fa1176e75fa7,60278120,Research and Production Center of Microbiology...,"Bogenbay batyr 105, Almaty, Kazakhstan",Kazakhstan
4,674efccd7ab4fa1176e75fa8,60277929,Vision College in Riyadh,"7211 Abdullah Al-Jasser – Ishbilia, Riyadh, Ar...",Saudi Arabia
...,...,...,...,...,...
11908,674f1f7e32601ca475ed8d6b,60027682,University of Sistan and Baluchestan,"Office of Corporate Affairs, Central Organizat...",Iran
11909,674f1f7f32601ca475ed8d6c,60027679,SOLEIL Synchrotron,"L'Orme des Merisiers, Gif-sur-Yvette, France",France
11910,674f1f8132601ca475ed8d6d,60027678,USDA ARS National Center for Agricultural Util...,"1815 N. University Street, Peoria, IL, United ...",United States
11911,674f1f8232601ca475ed8d6e,60027676,North Bristol NHS Trust,"Trust Headquarters, Southmead Hospital, Southm...",United Kingdom
11912,674f1f8432601ca475ed8d6f,60027675,Sahlgrenska Akademin,"Medicinaregatan 3, Gothenburg, Vastra Gotaland...",Sweden

In [22]:
paper_affiliation = paper_affiliation.merge(affiliation_country, how='inner', on='Affiliation')

In [23]:
paper_affiliation

,Eid,Affiliation,_id,affname,location,Country
0,2-s2.0-85053164279,60018465,674f034492fe4d3bb5a008ae,Yanshan University,"No. 438 West Hebei Avenue, Qinhuangdao, Hebei,...",China
1,2-s2.0-85053164279,60091507,674f160632601ca475ed8614,Metallurgy and Materials Research Institute Ch...,"Wangmai, Pathumwan, Soi Chula 12, Phyathai Roa...",Thailand
2,2-s2.0-85049101440,60028190,674f1f3232601ca475ed8d31,Chulalongkorn University,"Pathumwan, 254 Phayathai Road, Bangkok, Thailand",Thailand
3,2-s2.0-85054140369,60017165,674f042392fe4d3bb5a00951,Khon Kaen University,"Nai-Muang, 123 Moo 16 Mittraphap Rd, Khon Kaen...",Thailand
4,2-s2.0-85054140369,60026046,674efdff92fe4d3bb5a004b6,"Faculty of Medicine, Khon Kaen University","123 Mittraparp Highway, Khon Kaen, Thailand",Thailand
...,...,...,...,...,...,...
61264,2-s2.0-85150789915,60013939,674f069392fe4d3bb5a00b1b,"Faculty of Medicine, Thammasat University","Pathum Thani, Thailand",Thailand
61265,2-s2.0-85150789915,60199578,674efe8c7ab4fa1176e76101,Ramathibodi Hospital,Faculty of Medicine Ramathibodi Hospital Mahid...,Thailand
61266,2-s2.0-85165609857,60028190,674f1f3232601ca475ed8d31,Chulalongkorn University,"Pathumwan, 254 Phayathai Road, Bangkok, Thailand",Thailand
61267,2-s2.0-85164405594,60105841,674f06ef2175c93d72f1f43d,Al-Hussein Bin Talal University,"P.O. Box 20, Ma'an, Jordan",Jordan
61268,2-s2.0-85164405594,60028190,674f1f3232601ca475ed8d31,Chulalongkorn University,"Pathumwan, 254 Phayathai Road, Bangkok, Thailand",Thailand

In [24]:
paper_affiliation = paper_affiliation.groupby(['Eid','Country'])['_id'].count().reset_index().drop(columns='_id')

In [25]:
eid_list = paper_affiliation['Eid'].drop_duplicates().to_list()

In [26]:
relation = []

In [27]:
for i in eid_list:
    this_country = paper_affiliation[paper_affiliation['Eid'] == i]['Country'].to_list()
    for j in range(0, len(this_country)):
        for k in range(j + 1, len(this_country)):
            relation.append([min(this_country[j], this_country[k]), max(this_country[j], this_country[k]), 1])

In [28]:
relation

[['China', 'Nigeria', 1],
 ['China', 'Serbia', 1],
 ['China', 'Thailand', 1],
 ['Nigeria', 'Serbia', 1],
 ['Nigeria', 'Thailand', 1],
 ['Serbia', 'Thailand', 1],
 ['Thailand', 'United States', 1],
 ['Thailand', 'United Kingdom', 1],
 ['New Zealand', 'Thailand', 1],
 ['Thailand', 'United Kingdom', 1],
 ['Japan', 'Thailand', 1],
 ['Australia', 'Brazil', 1],
 ['Australia', 'Bulgaria', 1],
 ['Australia', 'France', 1],
 ['Australia', 'Netherlands', 1],
 ['Australia', 'Thailand', 1],
 ['Brazil', 'Bulgaria', 1],
 ['Brazil', 'France', 1],
 ['Brazil', 'Netherlands', 1],
 ['Brazil', 'Thailand', 1],
 ['Bulgaria', 'France', 1],
 ['Bulgaria', 'Netherlands', 1],
 ['Bulgaria', 'Thailand', 1],
 ['France', 'Netherlands', 1],
 ['France', 'Thailand', 1],
 ['Netherlands', 'Thailand', 1],
 ['Japan', 'Thailand', 1],
 ['Belgium', 'China', 1],
 ['Belgium', 'Cuba', 1],
 ['Belgium', 'Italy', 1],
 ['Belgium', 'Thailand', 1],
 ['China', 'Cuba', 1],
 ['China', 'Italy', 1],
 ['China', 'Thailand', 1],
 ['Cuba', 'Italy', 1],
 ['Cuba', 'Thailand', 1],
 ['Italy', 'Thailand', 1],
 ['Thailand', 'United Kingdom', 1],
 ['Thailand', 'United Kingdom', 1],
 ['Australia', 'Brazil', 1],
 ['Australia', 'Bulgaria', 1],
 ['Australia', 'France', 1],
 ['Australia', 'Netherlands', 1],
 ['Australia', 'Norway', 1],
 ['Australia', 'Thailand', 1],
 ['Australia', 'United Kingdom', 1],
 ['Brazil', 'Bulgaria', 1],
 ['Brazil', 'France', 1],
 ['Brazil', 'Netherlands', 1],
 ['Brazil', 'Norway', 1],
 ['Brazil', 'Thailand', 1],
 ['Brazil', 'United Kingdom', 1],
 ['Bulgaria', 'France', 1],
 ['Bulgaria', 'Netherlands', 1],
 ['Bulgaria', 'Norway', 1],
 ['Bulgaria', 'Thailand', 1],
 ['Bulgaria', 'United Kingdom', 1],
 ['France', 'Netherlands', 1],
 ['France', 'Norway', 1],
 ['France', 'Thailand', 1],
 ['France', 'United Kingdom', 1],
 ['Netherlands', 'Norway', 1],
 ['Netherlands', 'Thailand', 1],
 ['Netherlands', 'United Kingdom', 1],
 ['Norway', 'Thailand', 1],
 ['Norway', 'United Kingdom', 1],
 ['Thailand', 'United Kingdom', 1],
 ['Thailand', 'United States', 1],
 ['China', 'South Africa', 1],
 ['China', 'Thailand', 1],
 ['South Africa', 'Thailand', 1],
 ['China', 'South Africa', 1],
 ['China', 'Thailand', 1],
 ['South Africa', 'Thailand', 1],
 ['Australia', 'Brazil', 1],
 ['Australia', 'Bulgaria', 1],
 ['Australia', 'France', 1],
 ['Australia', 'Netherlands', 1],
 ['Australia', 'Thailand', 1],
 ['Australia', 'United Kingdom', 1],
 ['Brazil', 'Bulgaria', 1],
 ['Brazil', 'France', 1],
 ['Brazil', 'Netherlands', 1],
 ['Brazil', 'Thailand', 1],
 ['Brazil', 'United Kingdom', 1],
 ['Bulgaria', 'France', 1],
 ['Bulgaria', 'Netherlands', 1],
 ['Bulgaria', 'Thailand', 1],
 ['Bulgaria', 'United Kingdom', 1],
 ['France', 'Netherlands', 1],
 ['France', 'Thailand', 1],
 ['France', 'United Kingdom', 1],
 ['Netherlands', 'Thailand', 1],
 ['Netherlands', 'United Kingdom', 1],
 ['Thailand', 'United Kingdom', 1],
 ['Belgium', 'Malaysia', 1],
 ['Belgium', 'Thailand', 1],
 ['Belgium', 'United Kingdom', 1],
 ['Belgium', 'Viet Nam', 1],
 ['Malaysia', 'Thailand', 1],
 ['Malaysia', 'United Kingdom', 1],
 ['Malaysia', 'Viet Nam', 1],
 ['Thailand', 'United Kingdom', 1],
 ['Thailand', 'Viet Nam', 1],
 ['United Kingdom', 'Viet Nam', 1],
 ['Cambodia', 'Iran', 1],
 ['Cambodia', 'Japan', 1],
 ['Cambodia', 'Thailand', 1],
 ['Iran', 'Japan', 1],
 ['Iran', 'Thailand', 1],
 ['Japan', 'Thailand', 1],
 ['Australia', 'Thailand', 1],
 ['Brazil', 'United Kingdom', 1],
 ['Sweden', 'Thailand', 1],
 ['Japan', 'Thailand', 1],
 ['Poland', 'Thailand', 1],
 ['Poland', 'United Kingdom', 1],
 ['Thailand', 'United Kingdom', 1],
 ['Japan', 'Thailand', 1],
 ['Australia', 'Brazil', 1],
 ['Australia', 'Bulgaria', 1],
 ['Australia', 'Thailand', 1],
 ['Brazil', 'Bulgaria', 1],
 ['Brazil', 'Thailand', 1],
 ['Bulgaria', 'Thailand', 1],
 ['Thailand', 'United Kingdom', 1],
 ['Canada', 'Thailand', 1],
 ['France', 'Thailand', 1],
 ['Poland', 'Thailand', 1],
 ['Australia', 'Brazil', 1],
 ['Australia', 'Thailand', 1],
 ['Brazil', 'Thailand', 1],
 ['India', 'Japan', 1],
 ['India', 'Thailand', 1],
 ['Japan', 'Thailand', 1],
 ['Japan', 'Thailand', 1],
 ['Australia', 'Brazil', 1],
 ['Australia', 'Bulgaria', 1],
 ['Australia', 'Netherlands', 1],
 ['Australia', 'Thailand', 1],
 ['Australia', 'United Kingdom', 1],
 ['Australia', 'United States', 1],
 ['Brazil', 'Bulgaria', 1],
 ['Brazil', 'Netherlands', 1],
 ['Brazil', 'Thailand', 1],
 ['Brazil', 'United Kingdom', 1],
 ['Brazil', 'United States', 1],
 ['Bulgaria', 'Netherlands', 1],
 ['Bulgaria', 'Thailand', 1],
 ['Bulgaria', 'United Kingdom', 1],
 ['Bulgaria', 'United States', 1],
 ['Netherlands', 'Thailand', 1],
 ['Netherlands', 'United Kingdom', 1],
 ['Netherlands', 'United States', 1],
 ['Thailand', 'United Kingdom', 1],
 ['Thailand', 'United States', 1],
 ['United Kingdom', 'United States', 1],
 ['Australia', 'Brazil', 1],
 ['Australia', 'Bulgaria', 1],
 ['Australia', 'Italy', 1],
 ['Australia', 'Netherlands', 1],
 ['Australia', 'Thailand', 1],
 ['Australia', 'United Kingdom', 1],
 ['Brazil', 'Bulgaria', 1],
 ['Brazil', 'Italy', 1],
 ['Brazil', 'Netherlands', 1],
 ['Brazil', 'Thailand', 1],
 ['Brazil', 'United Kingdom', 1],
 ['Bulgaria', 'Italy', 1],
 ['Bulgaria', 'Netherlands', 1],
 ['Bulgaria', 'Thailand', 1],
 ['Bulgaria', 'United Kingdom', 1],
 ['Italy', 'Netherlands', 1],
 ['Italy', 'Thailand', 1],
 ['Italy', 'United Kingdom', 1],
 ['Netherlands', 'Thailand', 1],
 ['Netherlands', 'United Kingdom', 1],
 ['Thailand', 'United Kingdom', 1],
 ['Japan', 'Thailand', 1],
 ['South Korea', 'Thailand', 1],
 ['Australia', 'Spain', 1],
 ['Australia', 'Thailand', 1],
 ['Spain', 'Thailand', 1],
 ['Japan', 'Thailand', 1],
 ['Thailand', 'United States', 1],
 ['Japan', 'Thailand', 1],
 ['Japan', 'United States', 1],
 ['Thailand', 'United States', 1],
 ['Thailand', 'United Kingdom', 1],
 ['Argentina', 'Australia', 1],
 ['Argentina', 'Mexico', 1],
 ['Argentina', 'Poland', 1],
 ['Argentina', 'United Kingdom', 1],
 ['Australia', 'Mexico', 1],
 ['Australia', 'Poland', 1],
 ['Australia', 'United Kingdom', 1],
 ['Mexico', 'Poland', 1],
 ['Mexico', 'United Kingdom', 1],
 ['Poland', 'United Kingdom', 1],
 ['Thailand', 'United States', 1],
 ['Japan', 'Thailand', 1],
 ['Australia', 'Brazil', 1],
 ['Australia', 'Bulgaria', 1],
 ['Australia', 'Netherlands', 1],
 ['Australia', 'Poland', 1],
 ['Australia', 'Thailand', 1],
 ['Australia', 'United Kingdom', 1],
 ['Brazil', 'Bulgaria', 1],
 ['Brazil', 'Netherlands', 1],
 ['Brazil', 'Poland', 1],
 ['Brazil', 'Thailand', 1],
 ['Brazil', 'United Kingdom', 1],
 ['Bulgaria', 'Netherlands', 1],
 ['Bulgaria', 'Poland', 1],
 ['Bulgaria', 'Thailand', 1],
 ['Bulgaria', 'United Kingdom', 1],
 ['Netherlands', 'Poland', 1],
 ['Netherlands', 'Thailand', 1],
 ['Netherlands', 'United Kingdom', 1],
 ['Poland', 'Thailand', 1],
 ['Poland', 'United Kingdom', 1],
 ['Thailand', 'United Kingdom', 1],
 ['Thailand', 'United Kingdom', 1],
 ['Thailand', 'United States', 1],
 ['United Kingdom', 'United States', 1],
 ['Cambodia', 'Iran', 1],
 ['Cambodia', 'Japan', 1],
 ['Cambodia', 'Thailand', 1],
 ['Iran', 'Japan', 1],
 ['Iran', 'Thailand', 1],
 ['Japan', 'Thailand', 1],
 ['China', 'India', 1],
 ['China', 'Indonesia', 1],
 ['China', 'Singapore', 1],
 ['China', 'United States', 1],
 ['India', 'Indonesia', 1],
 ['India', 'Singapore', 1],
 ['India', 'United States', 1],
 ['Indonesia', 'Singapore', 1],
 ['Indonesia', 'United States', 1],
 ['Singapore', 'United States', 1],
 ['Australia', 'Brazil', 1],
 ['Australia', 'Bulgaria', 1],
 ['Australia', 'Netherlands', 1],
 ['Australia', 'Poland', 1],
 ['Australia', 'Thailand', 1],
 ['Australia', 'United Kingdom', 1],
 ['Brazil', 'Bulgaria', 1],
 ['Brazil', 'Netherlands', 1],
 ['Brazil', 'Poland', 1],
 ['Brazil', 'Thailand', 1],
 ['Brazil', 'United Kingdom', 1],
 ['Bulgaria', 'Netherlands', 1],
 ['Bulgaria', 'Poland', 1],
 ['Bulgaria', 'Thailand', 1],
 ['Bulgaria', 'United Kingdom', 1],
 ['Netherlands', 'Poland', 1],
 ['Netherlands', 'Thailand', 1],
 ['Netherlands', 'United Kingdom', 1],
 ['Poland', 'Thailand', 1],
 ['Poland', 'United Kingdom', 1],
 ['Thailand', 'United Kingdom', 1],
 ['France', 'Thailand', 1],
 ['France', 'United States', 1],
 ['Thailand', 'United States', 1],
 ['Thailand', 'United States', 1],
 ['Thailand', 'United Kingdom', 1],
 ['Thailand', 'Viet Nam', 1],
 ['Australia', 'Brazil', 1],
 ['Australia', 'Bulgaria', 1],
 ['Australia', 'Germany', 1],
 ['Australia', 'Thailand', 1],
 ['Australia', 'United Kingdom', 1],
 ['Brazil', 'Bulgaria', 1],
 ['Brazil', 'Germany', 1],
 ['Brazil', 'Thailand', 1],
 ['Brazil', 'United Kingdom', 1],
 ['Bulgaria', 'Germany', 1],
 ['Bulgaria', 'Thailand', 1],
 ['Bulgaria', 'United Kingdom', 1],
 ['Germany', 'Thailand', 1],
 ['Germany', 'United Kingdom', 1],
 ['Thailand', 'United Kingdom', 1],
 ['Japan', 'South Africa', 1],
 ['Japan', 'Thailand', 1],
 ['South Africa', 'Thailand', 1],
 ['Thailand', 'United Kingdom', 1],
 ['Japan', 'Thailand', 1],
 ['Japan', 'Thailand', 1],
 ['Japan', 'Thailand', 1],
 ['Japan', 'Viet Nam', 1],
 ['Thailand', 'Viet Nam', 1],
 ['Japan', 'Thailand', 1],
 ['Australia', 'Brazil', 1],
 ['Australia', 'Bulgaria', 1],
 ['Australia', 'France', 1],
 ['Australia', 'Netherlands', 1],
 ['Australia', 'Thailand', 1],
 ['Australia', 'United Kingdom', 1],
 ['Brazil', 'Bulgaria', 1],
 ['Brazil', 'France', 1],
 ['Brazil', 'Netherlands', 1],
 ['Brazil', 'Thailand', 1],
 ['Brazil', 'United Kingdom', 1],
 ['Bulgaria', 'France', 1],
 ['Bulgaria', 'Netherlands', 1],
 ['Bulgaria', 'Thailand', 1],
 ['Bulgaria', 'United Kingdom', 1],
 ['France', 'Netherlands', 1],
 ['France', 'Thailand', 1],
 ['France', 'United Kingdom', 1],
 ['Netherlands', 'Thailand', 1],
 ['Netherlands', 'United Kingdom', 1],
 ['Thailand', 'United Kingdom', 1],
 ['Australia', 'Bulgaria', 1],
 ['Australia', 'Netherlands', 1],
 ['Australia', 'Poland', 1],
 ['Australia', 'Thailand', 1],
 ['Bulgaria', 'Netherlands', 1],
 ['Bulgaria', 'Poland', 1],
 ['Bulgaria', 'Thailand', 1],
 ['Netherlands', 'Poland', 1],
 ['Netherlands', 'Thailand', 1],
 ['Poland', 'Thailand', 1],
 ['Thailand', 'Viet Nam', 1],
 ['Japan', 'Thailand', 1],
 ['France', 'Switzerland', 1],
 ['France', 'Thailand', 1],
 ['Switzerland', 'Thailand', 1],
 ['Indonesia', 'Thailand', 1],
 ['Thailand', 'United States', 1],
 ['India', 'Italy', 1],
 ['India', 'Poland', 1],
 ['India', 'Thailand', 1],
 ['Italy', 'Poland', 1],
 ['Italy', 'Thailand', 1],
 ['Poland', 'Thailand', 1],
 ['Australia', 'Brazil', 1],
 ['Australia', 'Bulgaria', 1],
 ['Australia', 'Thailand', 1],
 ['Australia', 'United Kingdom', 1],
 ['Brazil', 'Bulgaria', 1],
 ['Brazil', 'Thailand', 1],
 ['Brazil', 'United Kingdom', 1],
 ['Bulgaria', 'Thailand', 1],
 ['Bulgaria', 'United Kingdom', 1],
 ['Thailand', 'United Kingdom', 1],
 ['Thailand', 'United States', 1],
 ['Japan', 'Thailand', 1],
 ['Thailand', 'United States', 1],
 ['Belgium', 'China', 1],
 ['Belgium', 'Russian Federation', 1],
 ['Belgium', 'Singapore', 1],
 ['Belgium', 'Thailand', 1],
 ['China', 'Russian Federation', 1],
 ['China', 'Singapore', 1],
 ['China', 'Thailand', 1],
 ['Russian Federation', 'Singapore', 1],
 ['Russian Federation', 'Thailand', 1],
 ['Singapore', 'Thailand', 1],
 ['Japan', 'Thailand', 1],
 ['Thailand', 'Viet Nam', 1],
 ['Thailand', 'United States', 1],
 ['Japan', 'Thailand', 1],
 ['Japan', 'Thailand', 1],
 ['Japan', 'Thailand', 1],
 ['Thailand', 'United States', 1],
 ['Thailand', 'United States', 1],
 ['Australia', 'Brazil', 1],
 ['Australia', 'Canada', 1],
 ['Australia', 'Italy', 1],
 ['Australia', 'Spain', 1],
 ['Australia', 'Thailand', 1],
 ['Australia', 'United States', 1],
 ['Brazil', 'Canada', 1],
 ['Brazil', 'Italy', 1],
 ['Brazil', 'Spain', 1],
 ['Brazil', 'Thailand', 1],
 ['Brazil', 'United States', 1],
 ['Canada', 'Italy', 1],
 ['Canada', 'Spain', 1],
 ['Canada', 'Thailand', 1],
 ['Canada', 'United States', 1],
 ['Italy', 'Spain', 1],
 ['Italy', 'Thailand', 1],
 ['Italy', 'United States', 1],
 ['Spain', 'Thailand', 1],
 ['Spain', 'United States', 1],
 ['Thailand', 'United States', 1],
 ['China', 'Hong Kong', 1],
 ['China', 'Malaysia', 1],
 ['China', 'Philippines', 1],
 ['China', 'Singapore', 1],
 ['China', 'Thailand', 1],
 ['China', 'Viet Nam', 1],
 ['Hong Kong', 'Malaysia', 1],
 ['Hong Kong', 'Philippines', 1],
 ['Hong Kong', 'Singapore', 1],
 ['Hong Kong', 'Thailand', 1],
 ['Hong Kong', 'Viet Nam', 1],
 ['Malaysia', 'Philippines', 1],
 ['Malaysia', 'Singapore', 1],
 ['Malaysia', 'Thailand', 1],
 ['Malaysia', 'Viet Nam', 1],
 ['Philippines', 'Singapore', 1],
 ['Philippines', 'Thailand', 1],
 ['Philippines', 'Viet Nam', 1],
 ['Singapore', 'Thailand', 1],
 ['Singapore', 'Viet Nam', 1],
 ['Thailand', 'Viet Nam', 1],
 ['Australia', 'Brazil', 1],
 ['Australia', 'Thailand', 1],
 ['Australia', 'United Kingdom', 1],
 ['Brazil', 'Thailand', 1],
 ['Brazil', 'United Kingdom', 1],
 ['Thailand', 'United Kingdom', 1],
 ['China', 'Thailand', 1],
 ['Thailand', 'United States', 1],
 ['Thailand', 'United Kingdom', 1],
 ['Japan', 'Thailand', 1],
 ['Indonesia', 'Pakistan', 1],
 ['Indonesia', 'Thailand', 1],
 ['Pakistan', 'Thailand', 1],
 ['Brazil', 'India', 1],
 ['Brazil', 'United States', 1],
 ['India', 'United States', 1],
 ['India', 'Thailand', 1],
 ['Australia', 'Brazil', 1],
 ['Australia', 'Bulgaria', 1],
 ['Australia', 'Netherlands', 1],
 ['Australia', 'Poland', 1],
 ['Australia', 'Thailand', 1],
 ['Brazil', 'Bulgaria', 1],
 ['Brazil', 'Netherlands', 1],
 ['Brazil', 'Poland', 1],
 ['Brazil', 'Thailand', 1],
 ['Bulgaria', 'Netherlands', 1],
 ['Bulgaria', 'Poland', 1],
 ['Bulgaria', 'Thailand', 1],
 ['Netherlands', 'Poland', 1],
 ['Netherlands', 'Thailand', 1],
 ['Poland', 'Thailand', 1],
 ['Australia', 'Brazil', 1],
 ['Australia', 'Thailand', 1],
 ['Brazil', 'Thailand', 1],
 ['Japan', 'Thailand', 1],
 ['Japan', 'Viet Nam', 1],
 ['Thailand', 'Viet Nam', 1],
 ['Austria', 'Serbia', 1],
 ['Austria', 'Thailand', 1],
 ['Austria', 'Viet Nam', 1],
 ['Serbia', 'Thailand', 1],
 ['Serbia', 'Viet Nam', 1],
 ['Thailand', 'Viet Nam', 1],
 ['France', 'Thailand', 1],
 ['Thailand', 'United States', 1],
 ['Thailand', 'United States', 1],
 ['China', 'Russian Federation', 1],
 ['China', 'South Sudan', 1],
 ['China', 'Thailand', 1],
 ['Russian Federation', 'South Sudan', 1],
 ['Russian Federation', 'Thailand', 1],
 ['South Sudan', 'Thailand', 1],
 ['Austria', 'Thailand', 1],
 ['Belgium', 'Brazil', 1],
 ['Belgium', 'France', 1],
 ['Belgium', 'Romania', 1],
 ['Belgium', 'Sweden', 1],
 ['Belgium', 'Thailand', 1],
 ['Brazil', 'France', 1],
 ['Brazil', 'Romania', 1],
 ['Brazil', 'Sweden', 1],
 ['Brazil', 'Thailand', 1],
 ['France', 'Romania', 1],
 ['France', 'Sweden', 1],
 ['France', 'Thailand', 1],
 ['Romania', 'Sweden', 1],
 ['Romania', 'Thailand', 1],
 ['Sweden', 'Thailand', 1],
 ['Japan', 'Thailand', 1],
 ['Japan', 'Thailand', 1],
 ['Thailand', 'United States', 1],
 ['Taiwan', 'Thailand', 1],
 ['Australia', 'Japan', 1],
 ['Australia', 'Thailand', 1],
 ['Japan', 'Thailand', 1],
 ['Iceland', 'Japan', 1],
 ['Iceland', 'Thailand', 1],
 ['Japan', 'Thailand', 1],
 ['Australia', 'Brazil', 1],
 ['Australia', 'Bulgaria', 1],
 ['Australia', 'Thailand', 1],
 ['Australia', 'United Kingdom', 1],
 ['Brazil', 'Bulgaria', 1],
 ['Brazil', 'Thailand', 1],
 ['Brazil', 'United Kingdom', 1],
 ['Bulgaria', 'Thailand', 1],
 ['Bulgaria', 'United Kingdom', 1],
 ['Thailand', 'United Kingdom', 1],
 ['Austria', 'Thailand', 1],
 ['Japan', 'Thailand', 1],
 ['Canada', 'Thailand', 1],
 ['Thailand', 'United States', 1],
 ['Australia', 'Thailand', 1],
 ['Australia', 'United States', 1],
 ['Thailand', 'United States', 1],
 ['Japan', 'Thailand', 1],
 ['Japan', 'United States', 1],
 ['Thailand', 'United States', 1],
 ['Germany', 'Thailand', 1],
 ['China', 'Thailand', 1],
 ['Austria', 'Thailand', 1],
 ['Slovakia', 'Thailand', 1],
 ['India', 'Thailand', 1],
 ['France', 'Thailand', 1],
 ['Thailand', 'United States', 1],
 ['Belgium', 'Sweden', 1],
 ['Belgium', 'Switzerland', 1],
 ['Belgium', 'Thailand', 1],
 ['Belgium', 'United States', 1],
 ['Sweden', 'Switzerland', 1],
 ['Sweden', 'Thailand', 1],
 ['Sweden', 'United States', 1],
 ['Switzerland', 'Thailand', 1],
 ['Switzerland', 'United States', 1],
 ['Thailand', 'United States', 1],
 ['Japan', 'Thailand', 1],
 ['Thailand', 'United States', 1],
 ['South Korea', 'Thailand', 1],
 ['Cambodia', 'Hong Kong', 1],
 ['Cambodia', 'Sweden', 1],
 ['Cambodia', 'Thailand', 1],
 ['Cambodia', 'Viet Nam', 1],
 ['Hong Kong', 'Sweden', 1],
 ['Hong Kong', 'Thailand', 1],
 ['Hong Kong', 'Viet Nam', 1],
 ['Sweden', 'Thailand', 1],
 ['Sweden', 'Viet Nam', 1],
 ['Thailand', 'Viet Nam', 1],
 ['Indonesia', 'Thailand', 1],
 ['Indonesia', 'United States', 1],
 ['Thailand', 'United States', 1],
 ['Japan', 'Thailand', 1],
 ['Japan', 'Thailand', 1],
 ['Japan', 'United States', 1],
 ['Thailand', 'United States', 1],
 ['Australia', 'Thailand', 1],
 ['Armenia', 'Austria', 1],
 ['Armenia', 'Austria', 1],
 ['Japan', 'Thailand', 1],
 ['Thailand', 'United States', 1],
 ['China', 'South Africa', 1],
 ['China', 'Thailand', 1],
 ['South Africa', 'Thailand', 1],
 ['Thailand', 'United States', 1],
 ['Japan', 'Thailand', 1],
 ['Japan', 'United States', 1],
 ['Thailand', 'United States', 1],
 ['Thailand', 'United Kingdom', 1],
 ['South Korea', 'Thailand', 1],
 ['South Korea', 'Viet Nam', 1],
 ['Thailand', 'Viet Nam', 1],
 ['China', 'Thailand', 1],
 ['China', 'Japan', 1],
 ['China', 'Thailand', 1],
 ['Japan', 'Thailand', 1],
 ['Italy', 'Thailand', 1],
 ['Thailand', 'United States', 1],
 ['Japan', 'South Korea', 1],
 ['Japan', 'Thailand', 1],
 ['South Korea', 'Thailand', 1],
 ['China', 'Thailand', 1],
 ['Thailand', 'United States', 1],
 ['Australia', 'Bulgaria', 1],
 ['Australia', 'Netherlands', 1],
 ['Australia', 'Thailand', 1],
 ['Australia', 'United Kingdom', 1],
 ['Bulgaria', 'Netherlands', 1],
 ['Bulgaria', 'Thailand', 1],
 ['Bulgaria', 'United Kingdom', 1],
 ['Netherlands', 'Thailand', 1],
 ['Netherlands', 'United Kingdom', 1],
 ['Thailand', 'United Kingdom', 1],
 ['Switzerland', 'Thailand', 1],
 ['Switzerland', 'United Kingdom', 1],
 ['Switzerland', 'United States', 1],
 ['Thailand', 'United Kingdom', 1],
 ['Thailand', 'United States', 1],
 ['United Kingdom', 'United States', 1],
 ['Thailand', 'United States', 1],
 ['Thailand', 'United States', 1],
 ['Thailand', 'United States', 1],
 ['Thailand', 'United States', 1],
 ['Thailand', 'United States', 1],
 ['Thailand', 'United States', 1],
 ['Singapore', 'Thailand', 1],
 ['Australia', 'Brazil', 1],
 ['Australia', 'Bulgaria', 1],
 ['Australia', 'Netherlands', 1],
 ['Australia', 'Spain', 1],
 ['Australia', 'Thailand', 1],
 ['Australia', 'United Kingdom', 1],
 ['Brazil', 'Bulgaria', 1],
 ['Brazil', 'Netherlands', 1],
 ['Brazil', 'Spain', 1],
 ['Brazil', 'Thailand', 1],
 ['Brazil', 'United Kingdom', 1],
 ['Bulgaria', 'Netherlands', 1],
 ['Bulgaria', 'Spain', 1],
 ['Bulgaria', 'Thailand', 1],
 ['Bulgaria', 'United Kingdom', 1],
 ['Netherlands', 'Spain', 1],
 ['Netherlands', 'Thailand', 1],
 ['Netherlands', 'United Kingdom', 1],
 ['Spain', 'Thailand', 1],
 ['Spain', 'United Kingdom', 1],
 ['Thailand', 'United Kingdom', 1],
 ['Singapore', 'Thailand', 1],
 ['Thailand', 'United States', 1],
 ['Thailand', 'United States', 1],
 ['Thailand', 'United States', 1],
 ['Thailand', 'United Kingdom', 1],
 ['Thailand', 'United States', 1],
 ['Australia', 'Brazil', 1],
 ['Australia', 'Bulgaria', 1],
 ['Australia', 'Thailand', 1],
 ['Australia', 'United Kingdom', 1],
 ['Brazil', 'Bulgaria', 1],
 ['Brazil', 'Thailand', 1],
 ['Brazil', 'United Kingdom', 1],
 ['Bulgaria', 'Thailand', 1],
 ['Bulgaria', 'United Kingdom', 1],
 ['Thailand', 'United Kingdom', 1],
 ['Japan', 'Thailand', 1],
 ['Egypt', 'Thailand', 1],
 ['Egypt', 'United States', 1],
 ['Thailand', 'United States', 1],
 ['Thailand', 'United States', 1],
 ['Thailand', 'United States', 1],
 ['South Africa', 'Thailand', 1],
 ['Japan', 'Thailand', 1],
 ['Japan', 'Thailand', 1],
 ['Canada', 'Thailand', 1],
 ['Germany', 'Japan', 1],
 ['Germany', 'Thailand', 1],
 ['Japan', 'Thailand', 1],
 ['Netherlands', 'Thailand', 1],

In [29]:
relation_df = pd.DataFrame(relation, columns=['source', 'target', 'weight'])

relation_df

         source          target  weight
0         China         Nigeria       1
1         China          Serbia       1
2         China        Thailand       1
3       Nigeria          Serbia       1
4       Nigeria        Thailand       1
...         ...             ...     ...
31294   Nigeria  United Kingdom       1
31295    Rwanda        Thailand       1
31296    Rwanda  United Kingdom       1
31297  Thailand  United Kingdom       1
31298  Thailand  United Kingdom       1

[31299 rows x 3 columns]

In [30]:
relation_df = relation_df.groupby(['source', 'target'])['weight'].sum().reset_index()

In [31]:
relation_df.sort_values('weight', ascending=False)

         source          target  weight
2260   Thailand   United States    2340
1589      Japan        Thailand    1625
752       China        Thailand     912
2259   Thailand  United Kingdom     835
156   Australia        Thailand     807
...         ...             ...     ...
1101     Gambia   United States       1
1100     Gambia  United Kingdom       1
1099     Gambia    South Africa       1
1097     France         Uruguay       1
2294     Zambia        Zimbabwe       1

[2295 rows x 3 columns]

In [32]:
relation_df.to_csv('country_relation_from_top_10_seq.csv', index=False)