In [298]:
import pandas as pd

In [299]:
def cleaning_function_1(x):
    country_mapping = {
        'Thailand': 'Thailand',
        'THAILAND': 'Thailand',
        'Brazil': 'Brazil',
        'European Union': None,
        'Greece': 'Greece',
        'United States': 'United States',
        'Austria': 'Austria',
        'Italy': 'Italy',
        'Spain': 'Spain',
        'Finland': 'Finland',
        'Iran': 'Iran',
        'Mexico': 'Mexico',
        'Hungary': 'Hungary',
        'South Korea': 'South Korea',
        'Malaysia': 'Malaysia',
        'Colombia': 'Colombia',
        'Poland': 'Poland',
        'Belgium': 'Belgium',
        'Serbia': 'Serbia',
        'Switzerland': 'Switzerland',
        'Turkey': 'Turkey',
        'China': 'China',
        'Indonesia': 'Indonesia',
        'The United States': 'United States',
        'Germany': 'Germany',
        'The European Union': None,
        'France': 'France',
        'Czech Republic': 'Czech Republic',
        'Qatar': 'Qatar',
        'Hong Kong': 'Hong Kong',
        'Sweden': 'Sweden',
        'Japan': 'Japan',
        'Canada': 'Canada',
        'Nigeria': 'Nigeria',
        'India': 'India',
        'Vietnam': 'Vietnam',
        'Portugal': 'Portugal',
        'Australia': 'Australia',
        'Chile': 'Chile',
        'The Netherlands': 'Netherlands',
        'Russia': 'Russia',
        'Ecuador': 'Ecuador',
        'United Kingdom': 'United Kingdom',
        'South Africa': 'South Africa',
        'Latvia': 'Latvia',
        'Taiwan': 'Taiwan',
        'Ireland': 'Ireland',
        'Netherlands': 'Netherlands',
        'Argentina': 'Argentina',
        'Singapore': 'Singapore',
        'Montenegro': 'Montenegro',
        'Sri Lanka': 'Sri Lanka',
        'The United Kingdom': 'United Kingdom',
        'Brazil/Germany': 'Brazil',
        'Egypt': 'Egypt',
        'Thailand; Malaysia': 'Thailand',
    }

    if x in country_mapping:
        return country_mapping[x]
    else:
        return x

In [300]:
def cleaning_function_2(x):
    country_mapping = {
        'Thailand': 'Thailand',
        'Brazil': 'Brazil',
        'nan': None,
        'Greece': 'Greece',
        'United States': 'United States',
        'Austria': 'Austria',
        'Italy': 'Italy',
        'Spain': 'Spain',
        'Finland': 'Finland',
        'Iran': 'Iran',
        'Mexico': 'Mexico',
        'Hungary': 'Hungary',
        'South Korea': 'South Korea',
        'Malaysia': 'Malaysia',
        'Colombia': 'Colombia',
        'Poland': 'Poland',
        'Belgium': 'Belgium',
        'Serbia': 'Serbia',
        'Switzerland': 'Switzerland',
        'Turkey': 'Turkey',
        'China': 'China',
        'Indonesia': 'Indonesia',
        'Germany': 'Germany',
        'France': 'France',
        'Czech Republic': 'Czech Republic',
        'Qatar': 'Qatar',
        'Hong Kong': 'Hong Kong',
        'Sweden': 'Sweden',
        'Japan': 'Japan',
        'Canada': 'Canada',
        'Nigeria': 'Nigeria',
        'India': 'India',
        'Vietnam': 'Vietnam',
        'Portugal': 'Portugal',
        'Australia': 'Australia',
        'Chile': 'Chile',
        'Netherlands': 'Netherlands',
        'Russia': 'Russia',
        'Ecuador': 'Ecuador',
        'United Kingdom': 'United Kingdom',
        'South Africa': 'South Africa',
        'Latvia': 'Latvia',
        'Taiwan': 'Taiwan',
        'Ireland': 'Ireland',
        'Argentina': 'Argentina',
        'Singapore': 'Singapore',
        'Montenegro': 'Montenegro',
        'Sri Lanka': 'Sri Lanka',
        'Egypt': 'Egypt',
        'United Arab Emirates': 'United Arab Emirates',
        'Philippines': 'Philippines',
        'Iceland': 'Iceland',
        'Luxembourg': 'Luxembourg',
        'Laos': 'Laos',
        'Ukraine': 'Ukraine',
        'Uganda': 'Uganda',
        'Kenya': 'Kenya',
        'Cameroon': 'Cameroon',
        'Morocco': 'Morocco',
        'Bangladesh': 'Bangladesh',
        'Costa Rica': 'Costa Rica',
        'Monaco': 'Monaco',
        'New Zealand': 'New Zealand',
        'Panama': 'Panama',
        'Nepal': 'Nepal',
        'Denmark': 'Denmark',
        'Croatia': 'Croatia',
        'Slovakia': 'Slovakia',
        'Thailand and United Kingdom': 'Thailand',
        'Japan and South Korea': 'Japan',
        'Iraq': 'Iraq',
        'Israel': 'Israel',
        'Myanmar': 'Myanmar',
        'Pakistan': 'Pakistan',
        'Germany and Indonesia': 'Germany',
        'Cambodia': 'Cambodia',
        'Bulgaria': 'Bulgaria',
        'European Union: Belgium  \nAbbott: United States': 'Belgium',
        'Laos, Indonesia': 'Laos',
        'United States, Japan': 'United States',
        'Romania': 'Romania',
        'USA': 'United States',
        'United States, Switzerland': 'United States',
        'Saudi Arabia': 'Saudi Arabia',
        'The Philippines': 'Philippines',
        'Norway': 'Norway',
        'Estonia': 'Estonia',
        'Slovenia': 'Slovenia',
        'Myanmar: None  \nAustralia: Australia': 'Myanmar',
        'Belarus': 'Belarus',
        'United Kingdom, Thailand': 'United Kingdom',
        'Namibia': 'Namibia',
        'Kazakhstan': 'Kazakhstan',
        'Malawi': 'Malawi',
        'Singapore, United States': 'Singapore',
        'United States, Thailand': 'United States',
        'Cyprus': 'Cyprus',
        'United States and Germany': 'United States',
        'None.': None,
        "King Mongkut's University of Technology North Bangkok, Thailand": 'Thailand',
        'European Research Council - The United States': 'United States',
        'South Sudan': 'South Sudan',
        'The Southeast Asia-Europe Joint Funding Scheme for Research and Innovation is a collaborative effort between countries in Southeast Asia and Europe. However, since you are looking for one specific country and the scheme involves multiple countries from two regions, the answer to its specific location in terms of a single country is not applicable. If I have to choose one country where it is significant, I might incorrectly assign it to just one without proper representation of the others.\n\nFor an exact location based in one country, the answer would be \'None\'.': None,
        'Thailand.': 'Thailand',
        'European Research Council (ERC) is located in Belgium.': 'Belgium',
        'Papua New Guinea': 'Papua New Guinea',
        'Southeast Asia': None,
        'The National Security and Dual-Use Technology Center is likely located in Taiwan.': 'Taiwan',
        'The EASL Consortium for Regenerative Hepatology is associated with the European Association for the Study of the Liver (EASL), which is based in Switzerland.': 'Switzerland',
        'Germany, France': 'Germany',
        'Barbados': 'Barbados',
        'None ': None,
        'Eastern Caribbean Central Bank (ECCU) is located in Saint Kitts and Nevis.': 'Saint Kitts and Nevis',
        'European Union (EU)': None,
        'Syria': 'Syria',
        'Lithuania, Malaysia': 'Lithuania'
    }

    if x in country_mapping:
        return country_mapping[x]
    else:
        return x

In [301]:
def cleaning_function_3(x):
    country_mapping = {
        'Thailand': 'Thailand',
        'Brazil': 'Brazil',
        'Greece': 'Greece',
        'United States': 'United States',
        'Austria': 'Austria',
        'Italy': 'Italy',
        'Spain': 'Spain',
        'Finland': 'Finland',
        'Iran': 'Iran',
        'Mexico': 'Mexico',
        'Hungary': 'Hungary',
        'South Korea': 'South Korea',
        'Malaysia': 'Malaysia',
        'Colombia': 'Colombia',
        'Poland': 'Poland',
        'Belgium': 'Belgium',
        'Serbia': 'Serbia',
        'Switzerland': 'Switzerland',
        'Turkey': 'Turkey',
        'China': 'China',
        'Indonesia': 'Indonesia',
        'Germany': 'Germany',
        'France': 'France',
        'Czech Republic': 'Czech Republic',
        'Qatar': 'Qatar',
        'Hong Kong': 'Hong Kong',
        'Sweden': 'Sweden',
        'Japan': 'Japan',
        'Canada': 'Canada',
        'Nigeria': 'Nigeria',
        'India': 'India',
        'Vietnam': 'Vietnam',
        'Portugal': 'Portugal',
        'Australia': 'Australia',
        'Chile': 'Chile',
        'Netherlands': 'Netherlands',
        'Russia': 'Russia',
        'Ecuador': 'Ecuador',
        'United Kingdom': 'United Kingdom',
        'South Africa': 'South Africa',
        'Latvia': 'Latvia',
        'Taiwan': 'Taiwan',
        'Ireland': 'Ireland',
        'Argentina': 'Argentina',
        'Singapore': 'Singapore',
        'Montenegro': 'Montenegro',
        'Sri Lanka': 'Sri Lanka',
        'Egypt': 'Egypt',
        'United Arab Emirates': 'United Arab Emirates',
        'Philippines': 'Philippines',
        'Iceland': 'Iceland',
        'Luxembourg': 'Luxembourg',
        'Laos': 'Laos',
        'Ukraine': 'Ukraine',
        'Uganda': 'Uganda',
        'Kenya': 'Kenya',
        'Cameroon': 'Cameroon',
        'Morocco': 'Morocco',
        'Bangladesh': 'Bangladesh',
        'Costa Rica': 'Costa Rica',
        'Monaco': 'Monaco',
        'New Zealand': 'New Zealand',
        'Panama': 'Panama',
        'Nepal': 'Nepal',
        'Denmark': 'Denmark',
        'Croatia': 'Croatia',
        'Slovakia': 'Slovakia',
        'Iraq': 'Iraq',
        'Israel': 'Israel',
        'Myanmar': 'Myanmar',
        'Pakistan': 'Pakistan',
        'Cambodia': 'Cambodia',
        'Bulgaria': 'Bulgaria',
        'European Union: Belgium  \\nAbbott: United States': 'Belgium',
        'Romania': 'Romania',
        'Saudi Arabia': 'Saudi Arabia',
        'Norway': 'Norway',
        'Estonia': 'Estonia',
        'Slovenia': 'Slovenia',
        'Myanmar: None  \\nAustralia: Australia': 'Myanmar',
        'Belarus': 'Belarus',
        'Namibia': 'Namibia',
        'Kazakhstan': 'Kazakhstan',
        'Malawi': 'Malawi',
        'Cyprus': 'Cyprus',
        'South Sudan': 'South Sudan',
        "The Southeast Asia-Europe Joint Funding Scheme for Research and Innovation is a collaborative effort between countries in Southeast Asia and Europe. However, since you are looking for one specific country and the scheme involves multiple countries from two regions, the answer to its specific location in terms of a single country is not applicable. If I have to choose one country where it is significant, I might incorrectly assign it to just one without proper representation of the others.\n\nFor an exact location based in one country, the answer would be 'None'.": None,
        'Papua New Guinea': 'Papua New Guinea',
        'Barbados': 'Barbados',
        'Saint Kitts and Nevis': 'Saint Kitts and Nevis',
        'Syria': 'Syria',
        'Lithuania': 'Lithuania',
         "The Southeast Asia-Europe Joint Funding Scheme for Research and Innovation is a collaborative effort between countries in Southeast Asia and Europe. However, since you are looking for one specific country and the scheme involves multiple countries from two regions, the answer to its specific location in terms of a single country is not applicable. If I have to choose one country where it is significant, I might incorrectly assign it to just one without proper representation of the others.\\n\\nFor an exact location based in one country, the answer would be 'None'.": None

    }

    if x in country_mapping:
        return country_mapping[x]
    else:
        return x

In [302]:
funding_name_to_country_chat = pd.read_csv('Funding_Name_To_Country_Chat.csv').drop(columns='Unnamed: 0')
funding_name_to_country_chat

                                    funding_agency_name   Country
0                  Ratchadapisek Sompoch Endowment Fund  Thailand
1         Ministry for Science and Technology of Brazil    Brazil
2                          State University of Londrina    Brazil
3     Department of Chemical Engineering, Chulalongk...  Thailand
4                         Dow Chemical (Thailand), Ltd.  Thailand
...                                                 ...       ...
6204  Center of Scientific Equipment for Advanced Re...  Thailand
6205                            TU New Research Scholar  Thailand
6206  acknowledged and institute for research and de...  Thailand
6207                                               FAIR   Germany
6208                              Banrie Coffee Company  Thailand

[6209 rows x 2 columns]

In [303]:
funding_name_to_country_chat['Country'] = funding_name_to_country_chat['Country'].apply(lambda x : cleaning_function_1(x))

In [304]:
funding_name_to_country_chat['Country'] = funding_name_to_country_chat['Country'].apply(lambda x : cleaning_function_2(x))

In [305]:
funding_name_to_country_chat['Country'] = funding_name_to_country_chat['Country'].apply(lambda x : cleaning_function_3(x))

In [306]:
funding_name_to_country_chat = funding_name_to_country_chat.dropna()
funding_name_to_country_chat

                                    funding_agency_name   Country
0                  Ratchadapisek Sompoch Endowment Fund  Thailand
1         Ministry for Science and Technology of Brazil    Brazil
2                          State University of Londrina    Brazil
3     Department of Chemical Engineering, Chulalongk...  Thailand
4                         Dow Chemical (Thailand), Ltd.  Thailand
...                                                 ...       ...
6204  Center of Scientific Equipment for Advanced Re...  Thailand
6205                            TU New Research Scholar  Thailand
6206  acknowledged and institute for research and de...  Thailand
6207                                               FAIR   Germany
6208                              Banrie Coffee Company  Thailand

[6139 rows x 2 columns]

In [307]:
funding_name_to_country_list = funding_name_to_country_chat['Country'].drop_duplicates().to_list()

for i in funding_name_to_country_list:
    print(i)

Thailand
Brazil
Greece
United States
Austria
Italy
Spain
Finland
Iran
Mexico
Hungary
South Korea
Malaysia
Colombia
Poland
Belgium
Serbia
Switzerland
Turkey
China
Indonesia
Germany
France
Czech Republic
Qatar
Hong Kong
Sweden
Japan
Canada
Nigeria
India
Vietnam
Portugal
Australia
Chile
Netherlands
Russia
Ecuador
United Kingdom
South Africa
Latvia
Taiwan
Ireland
Argentina
Singapore
Montenegro
Sri Lanka
Egypt
United Arab Emirates
Philippines
Iceland
Luxembourg
Laos
Ukraine
Uganda
Kenya
Cameroon
Morocco
Bangladesh
Costa Rica
Monaco
New Zealand
Panama
Nepal
Denmark
Croatia
Slovakia
Iraq
Israel
Myanmar
Pakistan
Cambodia
Bulgaria
Romania
Saudi Arabia
Norway
Estonia
Slovenia
Belarus
Namibia
Kazakhstan
Malawi
Cyprus
South Sudan
Papua New Guinea
Barbados
Saint Kitts and Nevis
Syria
Lithuania

In [308]:
funding_name_to_country_chat.to_csv('Funding_Name_To_Country_Chat_Clean.csv')