In [1]:
import pandas as pd

In [2]:
old_data_index_term = pd.read_csv('../01_Combine_Data/Data_Index_Term.csv').rename(columns={"Idxterms" : "Index_Terms"})
new_data_index_term = pd.read_csv('Scrape_Index_Term.csv')

In [3]:
old_data_index_term

                      Eid                                        Index_Terms
0      2-s2.0-85053164279  304 stainless steel Capacitive behavior Corros...
1      2-s2.0-85049101440                                                ---
2      2-s2.0-85054140369  Adolescent Adult Aged Aged, 80 and over Child ...
3      2-s2.0-85097515350                                                ---
4      2-s2.0-85041527766  Catheterization Cholangiopancreatography, Endo...
...                   ...                                                ...
20211  2-s2.0-85152540548                                                ---
20212  2-s2.0-85132634561                                                ---
20213  2-s2.0-85150789915  Antineoplastic Combined Chemotherapy Protocols...
20214  2-s2.0-85165609857                                                ---
20215  2-s2.0-85164405594                                                ---

[20216 rows x 2 columns]

In [4]:
new_data_index_term

                     Eid                                        Index_Terms
0     2-s2.0-85029781991   Concretes Experimental program Fiber contents...
1     2-s2.0-85039703338   A-549 cell line A549 Cells Article CD51 antig...
2     2-s2.0-85039924338                                                ---
3     2-s2.0-85039922521                                                ---
4     2-s2.0-85039920890                                                ---
...                  ...                                                ...
1712  2-s2.0-84964267738   Adult Article Child Cone-Beam Computed Tomogr...
1713  2-s2.0-84922900576   climate change conceptual framework demograph...
1714  2-s2.0-84928152781   Thailand ecotoxicology environmental impact e...
1715  2-s2.0-84930797064                                                ---
1716  2-s2.0-84905892595   Average surface roughness Ball end milling Ba...

[1717 rows x 2 columns]

In [5]:
all_data_index_term = pd.concat([old_data_index_term, new_data_index_term])

In [6]:
all_data_index_term[all_data_index_term['Index_Terms'] == '---']

                     Eid Index_Terms
1     2-s2.0-85049101440         ---
3     2-s2.0-85097515350         ---
7     2-s2.0-85047155505         ---
11    2-s2.0-85054527535         ---
16    2-s2.0-85060184892         ---
...                  ...         ...
1644  2-s2.0-85010041725         ---
1662  2-s2.0-85008173386         ---
1672  2-s2.0-85007071638         ---
1700  2-s2.0-84992738280         ---
1715  2-s2.0-84930797064         ---

[9109 rows x 2 columns]

In [7]:
all_data_index_term.isna().sum()

Eid            0
Index_Terms    0
dtype: int64

In [8]:
all_data_index_term.to_csv('all_data_index_term.csv', index=False)